Adds verification check endpoint to change a user's `email verified` status (Server)
Adds an endpoint which takes an `email` string and an `authcode` string, which are compared against the database, rejecting if either are not equal.
Adds a function to update a given users `verified` flag field in the database, given some email.
Changes the build file to fail if the `go build` command fails, to catch errors before testing.

diff --git a/server/build b/server/build
--- a/server/build
+++ b/server/build
@@ -3,9 +3,15 @@ clear;
 #Sources the email provider environment variables
 source ./sendgrid.env;
 #Builds the server
-printf "\n\nBuilding the server binary...";
-go build -o main .;
-printf "\n\n";
-#Runs the server
-printf "\n\nRunning the server binary...";
-./main;
+echo "Building the server binary...";
+go build -o main .
+if [ $? -ne 0 ]; then
+    echo "Build failed!"
+else
+    echo "Build succeeded!"
+
+    #Runs the server
+    echo "Running the server binary...";
+    ./main;
+
+fi
